version: "2"
services:
  web:
    image: twang2218/gitlab-ce-zh:10.8.7
    #    hostname: 192.168.112.232
    ports:
    - 443:443
    - 81:80
    - 33:22
    volumes:
    - '/host_mnt/g/gitlab/config:/etc/gitlab'
    - '/host_mnt/g/gitlab/logs:/var/log/gitlab'
    - 'gitlab-data:/var/opt/gitlab'

volumes:
  gitlab-data:
    external: true
